#
# Academic License - for use in teaching, academic research, and meeting
# course requirements at degree granting institutions only.  Not for
# government, commercial, or other organizational use.
# File: calc_EKF_H_odom_optimized_simple.cpp
#
# MATLAB Coder version            : 3.4
# C/C++ source code generated on  : 26-Feb-2019 22:48:03
#

# Include Files
# include "rt_nonfinite.h"
# include "calc_EKF_H_odom_optimized_simple.h"

#
# CALC_EKF_H_ODOM_OPTIMIZED_SIMPLE
#     HODOM = CALC_EKF_H_ODOM_OPTIMIZED_SIMPLE(QLX,QLY,QLZ,RX,RY,RZ,VX,VY,VZ,OMEGAX,OMEGAY,OMEGAZ,MTOT,ITOTXX,ITOTYY,ITOTZZ,T_GEOMCOGX,T_GEOMCOGY,T_GEOMCOGZ,T_GEOMODOMX,T_GEOMODOMY,T_GEOMODOMZ,T_GEOMIMUX,T_GEOMIMUY,IMUBIASACCX,IMUBIASACCY,IMUBIASACCZ,IMUBIASANGVELX,IMUBIASANGVELY,IMUBIASANGVELZ,MOTOR1,MOTOR2,MOTOR3,MOTOR4,DT,T_GEOMIMUZ,W,L,C,K_F)
# Arguments    : double qLx
#                double qLy
#                double qLz
#                double rx
#                double ry
#                double rz
#                double vx
#                double vy
#                double vz
#                double Omegax
#                double Omegay
#                double Omegaz
#                double mtot
#                double Itotxx
#                double Itotyy
#                double Itotzz
#                double t_GeomCogX
#                double t_GeomCogY
#                double t_GeomCogZ
#                double t_GeomOdomX
#                double t_GeomOdomY
#                double t_GeomOdomZ
#                double t_GeomImuX
#                double t_GeomImuY
#                double ImuBiasAccX
#                double ImuBiasAccY
#                double ImuBiasAccZ
#                double ImuBiasAngVelX
#                double ImuBiasAngVelY
#                double ImuBiasAngVelZ
#                double motor1
#                double motor2
#                double motor3
#                double motor4
#                double dt
#                double t_GeomImuZ
#                double w
#                double l
#                double c
#                double k_f
#                double Hodom[90]
# Return Type  : void
#
import numpy as np
from numpy import sqrt, cos, sin


def calc_EKF_H_odom_optimized_simple(qLx: float, qLy: float, qLz: float,
                                     rx: float, ry: float, rz: float,
                                     vx: float, vy: float, vz: float,
                                     Omegax: float, Omegay: float, Omegaz: float,
                                     mtot: float,
                                     Itotxx: float, Itotyy: float, Itotzz: float,
                                     t_GeomCogX: float, t_GeomCogY: float, t_GeomCogZ: float,
                                     t_GeomOdomX: float, t_GeomOdomY: float, t_GeomOdomZ: float,
                                     t_GeomImuX: float, t_GeomImuY: float,
                                     ImuBiasAccX: float, ImuBiasAccY: float, ImuBiasAccZ: float,
                                     ImuBiasAngVelX: float, ImuBiasAngVelY: float, ImuBiasAngVelZ: float,
                                     motor1: float, motor2: float, motor3: float, motor4: float,
                                     dt: float, t_GeomImuZ: float, w: float, l: float, c: float, k_f: float,
                                     Hodom: np.ndarray):
    b_t10: np.ndarray = np.zeros(90)

    #     This function was generated by the Symbolic Math Toolbox version 8.
    #     26-Feb-2019 22:06:50
    t2 = qLy * qLy
    t3 = qLz * qLz
    t4 = qLx * qLx
    t5 = (t2 + t3) + t4
    t6 = sqrt(t5)
    t7 = cos(t6)
    t8 = sin(t6)
    t9 = pow(t5, 1.5)
    t10 = 1 / (t5 * t5)
    t11 = t2 * t2
    t12 = t3 * t3
    t13 = t6 * 0.5
    t14 = cos(t13)
    t15 = sin(t13)
    t16 = 1 / pow(t5, 1.5)
    t17 = t2 * t7
    t18 = t3 * t7
    t19 = (t4 + t17) + t18
    t20 = 1 / t5
    t13 = qLz * t3 * t14
    t5 = qLz * t4 * t14
    t23 = qLz * t2 * t14
    t47 = qLx * qLy * t6 * t15
    t25 = t15 * t16 * (((t13 + t5) + t23) - t47) * 2
    t26 = qLy * t2 * t14
    t27 = qLy * t4 * t14
    t28 = qLy * t3 * t14
    t29 = qLx * qLz * t6 * t15
    t30 = ((t26 + t27) + t28) + t29
    t31 = t4 * t4
    t32 = t8 * t9 * t_GeomOdomZ * 2
    t33 = t2 * t4 * t7 * t_GeomOdomZ * 2
    t34 = qLx * qLy * qLz * t_GeomCogZ * 4
    t35 = qLx * qLy * qLz * t7 * t_GeomOdomZ * 4
    t36 = qLx * qLy * qLz * t6 * t8 * t_GeomOdomZ * 2
    t37 = qLz * t3 * t_GeomCogZ * 2
    t38 = qLz * t4 * t_GeomOdomZ * 2
    t39 = qLz * t2 * t_GeomCogZ * 2
    t40 = qLz * t3 * t7 * t_GeomOdomZ * 2
    t41 = qLx * qLy * t2 * t7 * t_GeomCogZ * 2
    t42 = qLx * qLy * t4 * t7 * t_GeomCogZ * 2
    t43 = qLz * t4 * t7 * t_GeomCogZ * 2
    t44 = qLz * t2 * t7 * t_GeomOdomZ * 2
    t45 = qLx * qLy * t3 * t7 * t_GeomCogZ * 2
    t46 = qLx * qLy * t6 * t8 * t_GeomOdomZ * 2
    t48 = ((t13 + t5) + t23) + t47
    t49 = t4 * t7
    t50 = (t2 + t18) + t49
    t47 = qLx * t4 * t14
    t18 = qLx * t2 * t14
    t13 = qLx * t3 * t14
    t5 = qLy * qLz * t6 * t15
    t14 = t15 * t16 * (((t47 + t18) + t13) - t5) * 2
    t56 = t8 * t9 * t_GeomOdomY * 2
    t57 = t3 * t4 * t7 * t_GeomOdomY * 2
    t58 = qLx * qLy * qLz * t_GeomOdomY * 4
    t59 = qLx * qLy * qLz * t7 * t_GeomCogY * 4
    t60 = qLx * qLy * qLz * t6 * t8 * t_GeomCogY * 2
    t61 = t8 * t9 * t_GeomCogX * 2
    t62 = t2 * t3 * t7 * t_GeomCogX * 2
    t63 = qLx * qLy * qLz * t_GeomOdomX * 4
    t64 = qLx * qLy * qLz * t7 * t_GeomCogX * 4
    t65 = qLx * qLy * qLz * t6 * t8 * t_GeomCogX * 2
    t66 = qLx * t4 * t_GeomCogX * 2
    t67 = qLy * t2 * t_GeomCogY * 2
    t68 = qLx * t2 * t_GeomOdomX * 2
    t69 = qLy * t4 * t_GeomOdomY * 2
    t70 = qLx * t3 * t_GeomCogX * 2
    t71 = qLy * t3 * t_GeomCogY * 2
    t72 = qLx * t4 * t7 * t_GeomOdomX * 2
    t73 = qLy * t2 * t7 * t_GeomOdomY * 2
    t74 = qLx * t2 * t7 * t_GeomCogX * 2
    t75 = qLy * t4 * t7 * t_GeomCogY * 2
    t76 = qLx * t3 * t7 * t_GeomOdomX * 2
    t77 = qLx * qLz * t3 * t7 * t_GeomOdomY * 2
    t78 = qLx * qLz * t4 * t7 * t_GeomOdomY * 2
    t79 = qLy * qLz * t3 * t7 * t_GeomCogX * 2
    t80 = qLy * qLz * t2 * t7 * t_GeomCogX * 2
    t81 = qLy * t3 * t7 * t_GeomOdomY * 2
    t82 = qLy * qLz * t4 * t7 * t_GeomCogX * 2
    t83 = qLx * qLz * t2 * t7 * t_GeomOdomY * 2
    t84 = qLx * qLz * t6 * t8 * t_GeomCogY * 2
    t85 = qLy * qLz * t6 * t8 * t_GeomOdomX * 2
    t23 = t15 * t16 * (((t26 + t27) + t28) - t29) * 2
    t5 += (t47 + t18) + t13
    t13 = (t3 + t17) + t49
    b_t10[0] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((t37 + t38) + t39)
                                                                              + t40) + t41) + t42) + t43) + t44) + t45) + t46) + t67) + t69) + t71) + t73)
                                                                   + t75) + t77) + t78) + t81) + t83) + t84) + qLx * t2 * t_GeomCogX * 4) +
                                                            qLx * t3 * t_GeomCogX * 4) - qLx * t2 * t_GeomOdomX * 4) - qLx * t3 *
                                                          t_GeomOdomX * 4) - qLy * t4 * t_GeomCogY * 2) - qLy * t2 * t_GeomOdomY *
                                                        2) - qLy * t3 * t_GeomOdomY * 2) - qLz * t4 * t_GeomCogZ * 2) - qLz *
                                                     t2 * t_GeomOdomZ * 2) - qLz * t3 * t_GeomOdomZ * 2) - qLx * t2 * t7 *
                                                   t_GeomCogX * 4) - qLx * t3 * t7 * t_GeomCogX * 4) - qLx * t8 * t9 *
                                                 t_GeomCogX) + qLx * t2 * t7 * t_GeomOdomX * 4) + qLx * t3 * t7 *
                                               t_GeomOdomX * 4) + qLx * t8 * t9 * t_GeomOdomX) - qLy * t2 * t7 *
                                             t_GeomCogY * 2) - qLy * t3 * t7 * t_GeomCogY * 2) - qLy * t4 * t7 *
                                           t_GeomOdomY * 2) - qLz * t2 * t7 * t_GeomCogZ * 2) - qLz * t3 * t7 *
                                         t_GeomCogZ * 2) - qLz * t4 * t7 * t_GeomOdomZ * 2) - qLx * qLy * t6 * t8
                                       * t_GeomCogZ * 2) - qLx * qLy * t2 * t7 * t_GeomOdomZ *
                                      2) - qLx * qLy * t3 * t7 * t_GeomOdomZ * 2) - qLx * qLy
                                    * t4 * t7 * t_GeomOdomZ * 2) - qLx * qLz * t2 * t7 *
                                   t_GeomCogY * 2) - qLx * qLz * t3 * t7 * t_GeomCogY * 2) -
                                 qLx * qLz * t4 * t7 * t_GeomCogY * 2) - qLx * qLz * t6 * t8 *
                                t_GeomOdomY * 2) - qLx * t2 * t6 * t8 * t_GeomCogX) - qLx * t3 *
                              t6 * t8 * t_GeomCogX) + qLx * t4 * t6 * t8 * t_GeomCogX) + qLx * t2
                            * t6 * t8 * t_GeomOdomX) + qLx * t3 * t6 * t8 * t_GeomOdomX) - qLx *
                          t4 * t6 * t8 * t_GeomOdomX) + qLy * t4 * t6 * t8 * t_GeomCogY * 2) -
                        qLy * t4 * t6 * t8 * t_GeomOdomY * 2) + qLz * t4 * t6 * t8 * t_GeomCogZ
                       * 2) - qLz * t4 * t6 * t8 * t_GeomOdomZ * 2) * -0.5
    b_t10[1] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((t32 + t33) -
                                                                     t34) - t35) - t36) - qLx * t2 * t_GeomCogY * 4) + qLx * t2 * t_GeomOdomY *
                                                                 4) + qLy * t2 * t_GeomCogX * 2) + qLy * t3 * t_GeomCogX * 2) - qLy *
                                                              t4 * t_GeomCogX * 2) - qLy * t2 * t_GeomOdomX * 2) - qLy * t3 *
                                                            t_GeomOdomX * 2) + qLy * t4 * t_GeomOdomX * 2) - t8 * t9 * t_GeomCogZ *
                                                          2) - t7 * t31 * t_GeomCogZ * 2) + t7 * t31 * t_GeomOdomZ * 2) + qLx *
                                                       qLy * qLz * t_GeomOdomZ * 4) + qLx * t2 * t7 * t_GeomCogY * 4) - qLx *
                                                     t8 * t9 * t_GeomCogY) - qLx * t2 * t7 * t_GeomOdomY * 4) + qLx * t8 * t9 *
                                                   t_GeomOdomY) - qLy * t2 * t7 * t_GeomCogX * 2) - qLy * t3 * t7 *
                                                 t_GeomCogX * 2) + qLy * t4 * t7 * t_GeomCogX * 2) + qLy * t2 * t7 *
                                               t_GeomOdomX * 2) + qLy * t3 * t7 * t_GeomOdomX * 2) - qLy * t4 * t7 *
                                             t_GeomOdomX * 2) - t2 * t4 * t7 * t_GeomCogZ * 2) - t3 * t4 * t7 *
                                           t_GeomCogZ * 2) + t4 * t6 * t8 * t_GeomCogZ * 2) + t3 * t4 * t7 *
                                         t_GeomOdomZ * 2) - t4 * t6 * t8 * t_GeomOdomZ * 2) + qLx * qLy * qLz *
                                       t7 * t_GeomCogZ * 4) + qLx * qLz * t2 * t7 * t_GeomCogX * 2) + qLx * qLz
                                     * t3 * t7 * t_GeomCogX * 2) + qLx * qLz * t4 * t7 * t_GeomCogX * 2) -
                                   qLx * qLz * t6 * t8 * t_GeomCogX * 2) - qLx * qLz * t2 * t7 * t_GeomOdomX *
                                  2) - qLx * qLz * t3 * t7 * t_GeomOdomX * 2) - qLx * qLz * t4 * t7 *
                                t_GeomOdomX * 2) + qLx * qLz * t6 * t8 * t_GeomOdomX * 2) + qLx * t2 *
                              t6 * t8 * t_GeomCogY) - qLx * t3 * t6 * t8 * t_GeomCogY) - qLx * t4 * t6 *
                            t8 * t_GeomCogY) - qLx * t2 * t6 * t8 * t_GeomOdomY) + qLx * t3 * t6 * t8 *
                          t_GeomOdomY) + qLx * t4 * t6 * t8 * t_GeomOdomY) + qLy *
                        t4 * t6 * t8 * t_GeomCogX * 2) - qLy * t4 * t6 * t8 *
                       t_GeomOdomX * 2) + qLx * qLy * qLz * t6 * t8 * t_GeomCogZ
                      * 2) * -0.5
    b_t10[2] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((t56 + t57) -
                                                                     t58) - t59) - t60) + qLx * t3 * t_GeomCogZ * 4) - qLx * t3 * t_GeomOdomZ *
                                                                 4) - qLz * t2 * t_GeomCogX * 2) - qLz * t3 * t_GeomCogX * 2) + qLz *
                                                              t4 * t_GeomCogX * 2) + qLz * t2 * t_GeomOdomX * 2) + qLz * t3 *
                                                            t_GeomOdomX * 2) - qLz * t4 * t_GeomOdomX * 2) - t8 * t9 * t_GeomCogY *
                                                          2) - t7 * t31 * t_GeomCogY * 2) + t7 * t31 * t_GeomOdomY * 2) + qLx *
                                                       qLy * qLz * t_GeomCogY * 4) - qLx * t3 * t7 * t_GeomCogZ * 4) + qLx * t8
                                                     * t9 * t_GeomCogZ) + qLx * t3 * t7 * t_GeomOdomZ * 4) - qLx * t8 * t9 *
                                                   t_GeomOdomZ) + qLz * t2 * t7 * t_GeomCogX * 2) + qLz * t3 * t7 *
                                                 t_GeomCogX * 2) - qLz * t4 * t7 * t_GeomCogX * 2) - qLz * t2 * t7 *
                                               t_GeomOdomX * 2) - qLz * t3 * t7 * t_GeomOdomX * 2) + qLz * t4 * t7 *
                                             t_GeomOdomX * 2) - t2 * t4 * t7 * t_GeomCogY * 2) - t3 * t4 * t7 *
                                           t_GeomCogY * 2) + t4 * t6 * t8 * t_GeomCogY * 2) + t2 * t4 * t7 *
                                         t_GeomOdomY * 2) - t4 * t6 * t8 * t_GeomOdomY * 2) + qLx * qLy * qLz *
                                       t7 * t_GeomOdomY * 4) + qLx * qLy * t2 * t7 * t_GeomCogX * 2) + qLx *
                                     qLy * t3 * t7 * t_GeomCogX * 2) + qLx * qLy * t4 * t7 * t_GeomCogX * 2)
                                   - qLx * qLy * t6 * t8 * t_GeomCogX * 2) - qLx * qLy * t2 * t7 *
                                  t_GeomOdomX * 2) - qLx * qLy * t3 * t7 * t_GeomOdomX * 2) - qLx * qLy *
                                t4 * t7 * t_GeomOdomX * 2) + qLx * qLy * t6 * t8 * t_GeomOdomX * 2) +
                              qLx * t2 * t6 * t8 * t_GeomCogZ) - qLx * t3 * t6 * t8 * t_GeomCogZ) + qLx *
                            t4 * t6 * t8 * t_GeomCogZ) - qLx * t2 * t6 * t8 * t_GeomOdomZ) + qLx * t3 *
                          t6 * t8 * t_GeomOdomZ) - qLx * t4 * t6 * t8 *
                         t_GeomOdomZ) - qLz * t4 * t6 * t8 * t_GeomCogX * 2) +
                       qLz * t4 * t6 * t8 * t_GeomOdomX * 2) + qLx * qLy * qLz *
                      t6 * t8 * t_GeomOdomY * 2) * 0.5
    b_t10[3] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((t32 + t33) +
                                                                     t34) + t35) + t36) + qLx * t2 * t_GeomCogY * 2) - qLx * t3 * t_GeomCogY *
                                                                 2) - qLx * t4 * t_GeomCogY * 2) - qLx * t2 * t_GeomOdomY * 2) + qLx *
                                                              t3 * t_GeomOdomY * 2) + qLx * t4 * t_GeomOdomY * 2) + qLy * t4 *
                                                            t_GeomCogX * 4) - qLy * t4 * t_GeomOdomX * 4) - t8 * t9 * t_GeomCogZ *
                                                          2) - t7 * t11 * t_GeomCogZ * 2) + t7 * t11 * t_GeomOdomZ * 2) - qLx *
                                                       qLy * qLz * t_GeomOdomZ * 4) - qLx * t2 * t7 * t_GeomCogY * 2) + qLx *
                                                     t3 * t7 * t_GeomCogY * 2) + qLx * t4 * t7 * t_GeomCogY * 2) + qLx * t2 *
                                                   t7 * t_GeomOdomY * 2) - qLx * t3 * t7 * t_GeomOdomY * 2) - qLx * t4 * t7
                                                 * t_GeomOdomY * 2) - qLy * t4 * t7 * t_GeomCogX * 4) + qLy * t8 * t9 *
                                               t_GeomCogX) + qLy * t4 * t7 * t_GeomOdomX * 4) - qLy * t8 * t9 *
                                             t_GeomOdomX) - t2 * t3 * t7 * t_GeomCogZ * 2) - t2 * t4 * t7 * t_GeomCogZ *
                                           2) + t2 * t6 * t8 * t_GeomCogZ * 2) + t2 * t3 * t7 * t_GeomOdomZ * 2)
                                        - t2 * t6 * t8 * t_GeomOdomZ * 2) - qLx * qLy * qLz * t7 * t_GeomCogZ *
                                       4) + qLy * qLz * t2 * t7 * t_GeomCogY * 2) + qLy * qLz * t3 * t7 *
                                     t_GeomCogY * 2) + qLy * qLz * t4 * t7 * t_GeomCogY * 2) - qLy * qLz * t6
                                   * t8 * t_GeomCogY * 2) - qLy * qLz * t2 * t7 * t_GeomOdomY * 2) - qLy *
                                 qLz * t3 * t7 * t_GeomOdomY * 2) - qLy * qLz * t4 * t7 * t_GeomOdomY * 2)
                               + qLy * qLz * t6 * t8 * t_GeomOdomY * 2) - qLx * t2 * t6 * t8 * t_GeomCogY
                              * 2) + qLx * t2 * t6 * t8 * t_GeomOdomY * 2) + qLy * t2 * t6 * t8 *
                            t_GeomCogX) + qLy * t3 * t6 * t8 * t_GeomCogX) - qLy * t4 * t6 * t8 *
                          t_GeomCogX) - qLy * t2 * t6 * t8 * t_GeomOdomX) - qLy *
                        t3 * t6 * t8 * t_GeomOdomX) + qLy * t4 * t6 * t8 *
                       t_GeomOdomX) - qLx * qLy * qLz * t6 * t8 * t_GeomCogZ * 2) * 0.5
    b_t10[4] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((t37 - t38) - t39)
                                                                              + t40) - t41) - t42) - t43) - t44) - t45) - t46) + t66) + t68) + t70) + t72)
                                                                   + t74) + t76) + t79) + t80) + t82) + t85) - qLx * t2 * t_GeomCogX * 2) -
                                                            qLx * t3 * t_GeomOdomX * 2) - qLx * t4 * t_GeomOdomX * 2) + qLy * t3 *
                                                          t_GeomCogY * 4) + qLy * t4 * t_GeomCogY * 4) - qLy * t3 * t_GeomOdomY *
                                                        4) - qLy * t4 * t_GeomOdomY * 4) + qLz * t4 * t_GeomCogZ * 2) + qLz *
                                                     t2 * t_GeomOdomZ * 2) - qLz * t3 * t_GeomOdomZ * 2) - qLx * t3 * t7 *
                                                   t_GeomCogX * 2) - qLx * t4 * t7 * t_GeomCogX * 2) - qLx * t2 * t7 *
                                                 t_GeomOdomX * 2) - qLy * t3 * t7 * t_GeomCogY * 4) - qLy * t4 * t7 *
                                               t_GeomCogY * 4) - qLy * t8 * t9 * t_GeomCogY) + qLy * t3 * t7 *
                                             t_GeomOdomY * 4) + qLy * t4 * t7 * t_GeomOdomY * 4) + qLy * t8 * t9 *
                                           t_GeomOdomY) + qLz * t2 * t7 * t_GeomCogZ * 2) - qLz * t3 * t7 *
                                         t_GeomCogZ * 2) + qLz * t4 * t7 * t_GeomOdomZ * 2) + qLx * qLy * t6 * t8
                                       * t_GeomCogZ * 2) + qLx * qLy * t2 * t7 * t_GeomOdomZ *
                                      2) + qLx * qLy * t3 * t7 * t_GeomOdomZ * 2) + qLx * qLy
                                    * t4 * t7 * t_GeomOdomZ * 2) - qLy * qLz * t6 * t8 *
                                   t_GeomCogX * 2) - qLy * qLz * t2 * t7 * t_GeomOdomX * 2) -
                                 qLy * qLz * t3 * t7 * t_GeomOdomX * 2) - qLy * qLz * t4 * t7 *
                                t_GeomOdomX * 2) + qLx * t2 * t6 * t8 * t_GeomCogX * 2) - qLx
                              * t2 * t6 * t8 * t_GeomOdomX * 2) + qLy * t2 * t6 * t8 *
                             t_GeomCogY) - qLy * t3 * t6 * t8 * t_GeomCogY) - qLy * t4 * t6 * t8 *
                           t_GeomCogY) - qLy * t2 * t6 * t8 * t_GeomOdomY) + qLy * t3 * t6 * t8 *
                         t_GeomOdomY) + qLy * t4 * t6 * t8 * t_GeomOdomY) + qLz * t2 * t6 * t8 *
                       t_GeomCogZ * 2) - qLz * t2 * t6 * t8 * t_GeomOdomZ * 2) * -0.5
    b_t10[5] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((t61 + t62) -
                                                                     t63) - t64) - t65) + qLy * t3 * t_GeomCogZ * 4) - qLy * t3 * t_GeomOdomZ *
                                                                 4) + qLz * t2 * t_GeomCogY * 2) - qLz * t3 * t_GeomCogY * 2) - qLz *
                                                              t4 * t_GeomCogY * 2) - qLz * t2 * t_GeomOdomY * 2) + qLz * t3 *
                                                            t_GeomOdomY * 2) + qLz * t4 * t_GeomOdomY * 2) + t7 * t11 * t_GeomCogX *
                                                          2) - t8 * t9 * t_GeomOdomX * 2) - t7 * t11 * t_GeomOdomX * 2) + qLx *
                                                       qLy * qLz * t_GeomCogX * 4) - qLy * t3 * t7 * t_GeomCogZ * 4) + qLy * t8
                                                     * t9 * t_GeomCogZ) + qLy * t3 * t7 * t_GeomOdomZ * 4) - qLy * t8 * t9 *
                                                   t_GeomOdomZ) - qLz * t2 * t7 * t_GeomCogY * 2) + qLz * t3 * t7 *
                                                 t_GeomCogY * 2) + qLz * t4 * t7 * t_GeomCogY * 2) + qLz * t2 * t7 *
                                               t_GeomOdomY * 2) - qLz * t3 * t7 * t_GeomOdomY * 2) - qLz * t4 * t7 *
                                             t_GeomOdomY * 2) + t2 * t4 * t7 * t_GeomCogX * 2) - t2 * t6 * t8 *
                                           t_GeomCogX * 2) - t2 * t3 * t7 * t_GeomOdomX * 2) - t2 * t4 * t7 *
                                         t_GeomOdomX * 2) + t2 * t6 * t8 * t_GeomOdomX * 2) + qLx * qLy * qLz *
                                       t7 * t_GeomOdomX * 4) - qLx * qLy * t2 * t7 * t_GeomCogY * 2) - qLx *
                                     qLy * t3 * t7 * t_GeomCogY * 2) - qLx * qLy * t4 * t7 * t_GeomCogY * 2)
                                   + qLx * qLy * t6 * t8 * t_GeomCogY * 2) + qLx * qLy * t2 * t7 *
                                  t_GeomOdomY * 2) + qLx * qLy * t3 * t7 * t_GeomOdomY * 2) + qLx * qLy *
                                t4 * t7 * t_GeomOdomY * 2) - qLx * qLy * t6 * t8 * t_GeomOdomY * 2) +
                              qLy * t2 * t6 * t8 * t_GeomCogZ) - qLy * t3 * t6 * t8 * t_GeomCogZ) + qLy *
                            t4 * t6 * t8 * t_GeomCogZ) - qLy * t2 * t6 * t8 * t_GeomOdomZ) + qLy * t3 *
                          t6 * t8 * t_GeomOdomZ) - qLy * t4 * t6 * t8 *
                         t_GeomOdomZ) - qLz * t2 * t6 * t8 * t_GeomCogY * 2) +
                       qLz * t2 * t6 * t8 * t_GeomOdomY * 2) + qLx * qLy * qLz *
                      t6 * t8 * t_GeomOdomX * 2) * 0.5
    b_t10[6] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((t56 + t57) +
                                                                     t58) + t59) + t60) + qLx * t2 * t_GeomCogZ * 2) - qLx * t3 * t_GeomCogZ *
                                                                 2) + qLx * t4 * t_GeomCogZ * 2) - qLx * t2 * t_GeomOdomZ * 2) + qLx *
                                                              t3 * t_GeomOdomZ * 2) - qLx * t4 * t_GeomOdomZ * 2) - qLz * t4 *
                                                            t_GeomCogX * 4) + qLz * t4 * t_GeomOdomX * 4) - t8 * t9 * t_GeomCogY *
                                                          2) - t7 * t12 * t_GeomCogY * 2) + t7 * t12 * t_GeomOdomY * 2) - qLx *
                                                       qLy * qLz * t_GeomCogY * 4) - qLx * t2 * t7 * t_GeomCogZ * 2) + qLx * t3
                                                     * t7 * t_GeomCogZ * 2) - qLx * t4 * t7 * t_GeomCogZ * 2) + qLx * t2 * t7
                                                   * t_GeomOdomZ * 2) - qLx * t3 * t7 * t_GeomOdomZ * 2) + qLx * t4 * t7 *
                                                 t_GeomOdomZ * 2) + qLz * t4 * t7 * t_GeomCogX * 4) - qLz * t8 * t9 *
                                               t_GeomCogX) - qLz * t4 * t7 * t_GeomOdomX * 4) + qLz * t8 * t9 *
                                             t_GeomOdomX) - t2 * t3 * t7 * t_GeomCogY * 2) - t3 * t4 * t7 * t_GeomCogY *
                                           2) + t3 * t6 * t8 * t_GeomCogY * 2) + t2 * t3 * t7 * t_GeomOdomY * 2)
                                        - t3 * t6 * t8 * t_GeomOdomY * 2) - qLx * qLy * qLz * t7 * t_GeomOdomY *
                                       4) + qLy * qLz * t2 * t7 * t_GeomCogZ * 2) + qLy * qLz * t3 * t7 *
                                     t_GeomCogZ * 2) + qLy * qLz * t4 * t7 * t_GeomCogZ * 2) - qLy * qLz * t6
                                   * t8 * t_GeomCogZ * 2) - qLy * qLz * t2 * t7 * t_GeomOdomZ * 2) - qLy *
                                 qLz * t3 * t7 * t_GeomOdomZ * 2) - qLy * qLz * t4 * t7 * t_GeomOdomZ * 2)
                               + qLy * qLz * t6 * t8 * t_GeomOdomZ * 2) + qLx * t3 * t6 * t8 * t_GeomCogZ
                              * 2) - qLx * t3 * t6 * t8 * t_GeomOdomZ * 2) - qLz * t2 * t6 * t8 *
                            t_GeomCogX) - qLz * t3 * t6 * t8 * t_GeomCogX) + qLz * t4 * t6 * t8 *
                          t_GeomCogX) + qLz * t2 * t6 * t8 * t_GeomOdomX) + qLz *
                        t3 * t6 * t8 * t_GeomOdomX) - qLz * t4 * t6 * t8 *
                       t_GeomOdomX) - qLx * qLy * qLz * t6 * t8 * t_GeomOdomY *
                      2) * -0.5
    b_t10[7] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((t61 + t62) +
                                                                     t63) + t64) + t65) + qLy * t2 * t_GeomCogZ * 2) - qLy * t3 * t_GeomCogZ *
                                                                 2) + qLy * t4 * t_GeomCogZ * 2) - qLy * t2 * t_GeomOdomZ * 2) + qLy *
                                                              t3 * t_GeomOdomZ * 2) - qLy * t4 * t_GeomOdomZ * 2) - qLz * t2 *
                                                            t_GeomCogY * 4) + qLz * t2 * t_GeomOdomY * 4) + t7 * t12 * t_GeomCogX *
                                                          2) - t8 * t9 * t_GeomOdomX * 2) - t7 * t12 * t_GeomOdomX * 2) - qLx *
                                                       qLy * qLz * t_GeomCogX * 4) - qLy * t2 * t7 * t_GeomCogZ * 2) + qLy * t3
                                                     * t7 * t_GeomCogZ * 2) - qLy * t4 * t7 * t_GeomCogZ * 2) + qLy * t2 * t7
                                                   * t_GeomOdomZ * 2) - qLy * t3 * t7 * t_GeomOdomZ * 2) + qLy * t4 * t7 *
                                                 t_GeomOdomZ * 2) + qLz * t2 * t7 * t_GeomCogY * 4) - qLz * t8 * t9 *
                                               t_GeomCogY) - qLz * t2 * t7 * t_GeomOdomY * 4) + qLz * t8 * t9 *
                                             t_GeomOdomY) + t3 * t4 * t7 * t_GeomCogX * 2) - t3 * t6 * t8 * t_GeomCogX *
                                           2) - t2 * t3 * t7 * t_GeomOdomX * 2) - t3 * t4 * t7 * t_GeomOdomX * 2)
                                        + t3 * t6 * t8 * t_GeomOdomX * 2) - qLx * qLy * qLz * t7 * t_GeomOdomX *
                                       4) - qLx * qLz * t2 * t7 * t_GeomCogZ * 2) - qLx * qLz * t3 * t7 *
                                     t_GeomCogZ * 2) - qLx * qLz * t4 * t7 * t_GeomCogZ * 2) + qLx * qLz * t6
                                   * t8 * t_GeomCogZ * 2) + qLx * qLz * t2 * t7 * t_GeomOdomZ * 2) + qLx *
                                 qLz * t3 * t7 * t_GeomOdomZ * 2) + qLx * qLz * t4 * t7 * t_GeomOdomZ * 2)
                               - qLx * qLz * t6 * t8 * t_GeomOdomZ * 2) + qLy * t3 * t6 * t8 * t_GeomCogZ
                              * 2) - qLy * t3 * t6 * t8 * t_GeomOdomZ * 2) + qLz * t2 * t6 * t8 *
                            t_GeomCogY) - qLz * t3 * t6 * t8 * t_GeomCogY) - qLz * t4 * t6 * t8 *
                          t_GeomCogY) - qLz * t2 * t6 * t8 * t_GeomOdomY) + qLz *
                        t3 * t6 * t8 * t_GeomOdomY) + qLz * t4 * t6 * t8 *
                       t_GeomOdomY) - qLx * qLy * qLz * t6 * t8 * t_GeomOdomX *
                      2) * -0.5
    b_t10[8] = t10 * (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((t66 + t67) - t68)
                                                                              - t69) - t70) - t71) + t72) + t73) - t74) - t75) - t76) - t77) - t78) - t79)
                                                                   - t80) - t81) - t82) - t83) - t84) - t85) + qLx * t2 * t_GeomCogX * 2) +
                                                            qLx * t3 * t_GeomOdomX * 2) - qLx * t4 * t_GeomOdomX * 2) + qLy * t4 *
                                                          t_GeomCogY * 2) - qLy * t2 * t_GeomOdomY * 2) + qLy * t3 * t_GeomOdomY *
                                                        2) + qLz * t2 * t_GeomCogZ * 4) + qLz * t4 * t_GeomCogZ * 4) - qLz *
                                                     t2 * t_GeomOdomZ * 4) - qLz * t4 * t_GeomOdomZ * 4) + qLx * t3 * t7 *
                                                   t_GeomCogX * 2) - qLx * t4 * t7 * t_GeomCogX * 2) + qLx * t2 * t7 *
                                                 t_GeomOdomX * 2) - qLy * t2 * t7 * t_GeomCogY * 2) + qLy * t3 * t7 *
                                               t_GeomCogY * 2) + qLy * t4 * t7 * t_GeomOdomY * 2) - qLz * t2 * t7 *
                                             t_GeomCogZ * 4) - qLz * t4 * t7 * t_GeomCogZ * 4) - qLz * t8 * t9 *
                                           t_GeomCogZ) + qLz * t2 * t7 * t_GeomOdomZ * 4) + qLz * t4 * t7 *
                                         t_GeomOdomZ * 4) + qLz * t8 * t9 * t_GeomOdomZ) + qLx * qLz * t2 * t7 *
                                       t_GeomCogY * 2) + qLx * qLz * t3 * t7 * t_GeomCogY * 2)
                                     + qLx * qLz * t4 * t7 * t_GeomCogY * 2) + qLx * qLz * t6 *
                                    t8 * t_GeomOdomY * 2) + qLy * qLz * t6 * t8 * t_GeomCogX *
                                   2) + qLy * qLz * t2 * t7 * t_GeomOdomX * 2) + qLy * qLz *
                                 t3 * t7 * t_GeomOdomX * 2) + qLy * qLz * t4 * t7 * t_GeomOdomX
                                * 2) + qLx * t3 * t6 * t8 * t_GeomCogX * 2) - qLx * t3 * t6 *
                              t8 * t_GeomOdomX * 2) + qLy * t3 * t6 * t8 * t_GeomCogY * 2) -
                            qLy * t3 * t6 * t8 * t_GeomOdomY * 2) - qLz * t2 * t6 * t8 *
                           t_GeomCogZ) + qLz * t3 * t6 * t8 * t_GeomCogZ) - qLz * t4 * t6 * t8 *
                         t_GeomCogZ) + qLz * t2 * t6 * t8 * t_GeomOdomZ) - qLz * t3 * t6 * t8 *
                       t_GeomOdomZ) + qLz * t4 * t6 * t8 * t_GeomOdomZ) * -0.5
    b_t10[9] = 1
    b_t10[10] = 0
    b_t10[11] = 0
    b_t10[12] = 0
    b_t10[13] = 1
    b_t10[14] = 0
    b_t10[15] = 0
    b_t10[16] = 0
    b_t10[17] = 1
    b_t10[18:48] = 0
    b_t10[48] = -t19 * t20
    b_t10[49] = t15 * t16 * t48 * -2
    b_t10[50] = t23
    b_t10[51] = t25
    b_t10[52] = -t20 * t50
    b_t10[53] = t15 * t16 * t5 * -2
    b_t10[54] = t15 * t16 * t30 * -2
    b_t10[55] = t14
    b_t10[56] = -t20 * t13
    b_t10[57] = t19 * t20
    b_t10[58] = t15 * t16 * t48 * 2
    b_t10[59] = -t23
    b_t10[60] = -t25
    b_t10[61] = t20 * t50
    b_t10[62] = t15 * t16 * t5 * 2
    b_t10[63] = t15 * t16 * t30 * 2
    b_t10[64] = -t14
    b_t10[65] = t20 * t13
    b_t10[66:90] = 0
    for i0 in range(90):
        Hodom[i0] = b_t10[i0]
    return Hodom
